# Generated by Django 4.2.6 on 2023-11-14 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='them',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Task.theme'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Task.typeanswer'),
        ),
    ]
