# Generated by Django 4.2.6 on 2023-11-21 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='them',
            new_name='theme',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='type_ans',
        ),
        migrations.AlterModelTable(
            name='theme',
            table='theme',
        ),
    ]
