# Generated by Django 4.2.6 on 2023-11-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_them_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='them',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.theme'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.typeanswer'),
        ),
    ]
