# Generated by Django 4.2.6 on 2023-11-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='None', null=True, upload_to='user_photos/'),
        ),
    ]
