# Generated by Django 4.2.6 on 2023-11-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_count_tasks_alter_user_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='count_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_url',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='User.userrole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
