# Generated by Django 4.2.6 on 2023-11-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_count_tasks_alter_user_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
