# Generated by Django 4.2.6 on 2023-11-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
